(async () => {
  assert(parseSchoolStr('FLAT PENDIDIKAN').name === 'FLAT PENDIDIKAN', 'Uncoded school retained');
  assert(!isSchoolMatch('YBA1234 SK CONTOH', ''), 'Blank school cannot match');
  assert(!isSchoolMatch('YBA1234 SK CONTOH', 'YBA5678 SK CONTOH 2'), 'Different schools stay isolated');
  assert(JSON.stringify(getSpecialSchoolOptions('Y050 FLAT PENDIDIKAN')) === JSON.stringify(['Blok A', 'Blok B', 'Blok C']), 'Flat Pendidikan has Blok A, B and C');
  assert(getSpecialSchoolOptions('YEA5101 SEKOLAH MENENGAH KEBANGSAAN SERI PATIAMBUN').includes('Rumah Pengetua'), 'Full imported SMK Seri Patiambun name gets special quarters');
  assert(getSpecialSchoolOptions('YEA5102 SEKOLAH MENENGAH KEBANGSAAN KUBONG').includes('Rumah PK HEM'), 'Full imported SMK Kubong name gets special quarters');
  assert(getSpecialSchoolOptions('YEB5101 SEKOLAH MENENGAH KEBANGSAAN MEDAMIT').includes('Flat Lama E'), 'Full imported SMK Medamit name gets special quarters');
  assert(getSpecialSchoolOptions('YEE5101 SEKOLAH MENENGAH KEBANGSAAN LIMBANG').includes('Flat Junior'), 'Full imported SMK Limbang name gets special quarters');
  assert(getSpecialSchoolOptions('YRA5101 SEKOLAH MENENGAH KEBANGSAAN AGAMA LIMBANG').includes('Flat D'), 'Full imported SMK Agama Limbang name gets Flat D special quarters');
  const vacant = normalizeOccupancy({ statusHunian: 'Tidak Berpenghuni', bilanganBilik: 3, noKP: 'private', bilik1Status: 'Diisi', bilik1Penghuni: 'Name', ketuaRumah: 'bilik1' });
  assert(vacant.noKP === '' && vacant.bilik1Penghuni === '' && vacant.ketuaRumah === '', 'Vacancy clears personal data');
  assert(normalizeOccupancy({ statusHunian: 'Tidak Berpenghuni', bilanganBilik: 3, bilik1Status: 'Rosak' }).bilik1Status === 'Kosong', 'Vacancy clears shared room status');
  render(); await settle();
  assert(queryCount === 0, 'No database requests before authentication');
  assert(!model.loading && !model.isAuthenticated, 'Login ready without session');
  model.setLoginUsername('school@example.com'); model.setLoginPassword('wrong'); render();
  await model.handleLogin(event); await settle();
  assert(!model.isAuthenticated && !!model.loginError, 'Invalid password cannot log in');
  model.setLoginPassword('test-password'); render();
  await model.handleLogin(event); await settle();
  assert(model.isAuthenticated && model.authUser.schoolId === 'school-a', 'Auth profile supplies school identity');
  assert(model.loginPassword === '', 'Password cleared after successful login');
  assert(fixtures.esipk_login_logs.length === 2, 'School login writes login activity log');
  assert(model.submissions.length === 1, 'Data loads after authentication');
  window.location.hash = '/settings'; render(); assert(model.view === 'dashboard', 'School settings route denied');
  window.location.hash = '/logAktiviti'; render(); assert(model.view === 'dashboard', 'School activity log route denied');
  const record = model.submissions[0];
  model.handleEditRow(record); render(); model.navigate('form'); render();
  assert(model.editingRecordId === record.id, 'Active form navigation retains edit ID');
  model.handleChange({ target: { name: 'bilik1Status', value: 'Diisi', type: 'select-one' } }); render();
  model.handleChange({ target: { name: 'bilik1Penghuni', value: 'Nama Bilik', type: 'text' } }); render();
  model.handleChange({ target: { name: 'namaPenghuni', value: 'Nama Utama', type: 'text' } }); render();
  model.handleChange({ target: { name: 'statusHunian', value: 'Tidak Berpenghuni', type: 'radio' } }); render();
  assert(model.formData.bilik1Status === 'Kosong' && model.formData.bilik1Penghuni === '' && model.formData.namaPenghuni === '', 'Vacant status clears occupancy fields immediately');
  model.handleChange({ target: { name: 'namaKuarters', value: 'Updated', type: 'text' } }); render();
  authListener('SIGNED_IN', activeSession); await settle();
  assert(model.editingRecordId === record.id && model.formData.namaKuarters === 'Updated', 'Repeated Auth events preserve unsaved form');
  assert(fixtures.esipk_login_logs.length === 2, 'Repeated signed-in event does not duplicate login log');
  failNextMutation = true;
  await model.handleSubmit(event); await settle();
  assert(fixtures.esipk_quarters[0].data.namaKuarters === 'Unit A', 'Failed write leaves stored record intact');
  assert(model.editingRecordId === record.id, 'Failed save retains edit form');
  await model.handleSubmit(event); await settle();
  assert(fixtures.esipk_quarters.length === 1 && fixtures.esipk_quarters[0].data.namaKuarters === 'Updated', 'Edit saves without duplication');
  assert(fixtures.esipk_quarters[0].school_id === 'school-a', 'Immutable school FK sent to database');
  assert(!('namaSekolah' in fixtures.esipk_quarters[0].data), 'Mutable school display name not stored in payload');
  assert(!('createdAtDate' in fixtures.esipk_quarters[0].data), 'Server controls timestamps');
  model.setSelectedUnit(record); model.setStatusFilter('Dihuni'); render();
  await model.handleLogout(); await settle();
  assert(!model.isAuthenticated && model.submissions.length === 0 && model.selectedUnit === null && model.loginLogs.length === 0, 'Logout clears private data');
  assert(model.statusFilter === 'Semua', 'Logout clears filters');
  model.setLoginUsername('admin@example.com'); model.setLoginPassword('test-password'); render();
  await model.handleLogin(event); await settle(); model.navigate('settings'); render();
  assert(model.authUser.type === 'admin' && model.view !== 'settings', 'Other admin cannot open settings');
  assert(!isSettingsAdmin({ type: 'school', email: 'admin@moe.gov.my' }), 'Email alone cannot grant settings access');
  await model.handleLogout(); await settle();
  model.setLoginUsername('admin@moe.gov.my'); model.setLoginPassword('test-password'); render();
  await model.handleLogin(event); await settle(); model.navigate('settings'); render();
  assert(model.view === 'settings', 'Designated PPD administrator can open settings');
  model.navigate('logAktiviti'); render();
  assert(model.view === 'logAktiviti' && model.loginLogs.length >= 1, 'Admin can open login activity log');
  assert(await resolveAttachmentUrl('javascript:alert(1)') === '', 'Unsafe attachment protocol rejected');
  let rejected = false; try { await runGas('resetSchools'); } catch (_) { rejected = true; }
  assert(rejected, 'Bulk school reset disabled');
  print('PASS: ' + assertions + ' regression assertions');
})().catch(error => print('FAIL: ' + error.stack));
