#!/usr/bin/env python3
"""Build the Apps Script-compatible HTML using a local, pinned JSX compiler."""
from pathlib import Path
import json
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
SOURCES = [
    'config.js', 'lib/utils.js', 'lib/api.js', 'lib/supabase.js', 'components/Icons.jsx',
    'components/ErrorBoundary.jsx', 'components/TopNavLink.jsx',
    'useDashboard.js', 'pages/LoginPage.jsx', 'pages/DashboardPage.jsx',
    'pages/FormPage.jsx', 'pages/DownloadsPage.jsx', 'pages/SettingsPage.jsx',
    'components/Attachment.jsx', 'components/UnitDetails.jsx', 'App.jsx',
]

def build():
    source = '(() => {\nconst { useState, useEffect, useMemo, useRef } = React;\n' + '\n'.join(
        (ROOT / 'src' / name).read_text() for name in SOURCES
    ) + '\n})();'
    node = shutil.which('node')
    jsc = '/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Helpers/jsc'
    if not node and not Path(jsc).exists():
        raise SystemExit('Install Node.js to run the pinned compiler, then rerun python3 tools/build.py.')
    with tempfile.TemporaryDirectory() as folder:
        folder = Path(folder)
        source_path = folder / 'source.jsx'
        output_path = folder / 'application.js'
        source_path.write_text(source)
        compiler = str(ROOT / 'tools/vendor/babel.min.js')
        # Validate unbound identifiers as well as JSX syntax before building.
        transform = '''
const allowed = new Set(['React','ReactDOM','window','document','google','localStorage','FileReader','setTimeout','clearTimeout','console']);
const errors = new Set();
const result = Babel.transform(input, {
  presets: [['react', { runtime: 'classic' }]], comments: false, compact: true,
  plugins: [function() { return { visitor: { ReferencedIdentifier(path) {
    const name = path.node.name;
    if (!path.scope.hasBinding(name) && !allowed.has(name)) errors.add(name);
  } } }; }]
});
if (errors.size) throw new Error('Unbound identifiers: ' + [...errors].join(', '));
'''
        if node:
            driver = f"const fs = require('fs'); const Babel = require({json.dumps(compiler)}); const input = fs.readFileSync({json.dumps(str(source_path))}, 'utf8');\n" + transform + f"\nfs.writeFileSync({json.dumps(str(output_path))}, result.code);"
        else:
            driver = "var console = { debug: function(){}, log: print, warn: print, error: print };\n" + f"load({json.dumps(compiler)}); const input = readFile({json.dumps(str(source_path))});\n" + transform + f"\nprint(result.code);"
        driver_path = folder / 'compile.js'
        driver_path.write_text(driver)
        result = subprocess.run([node or jsc, str(driver_path)], capture_output=True, text=True)
        if result.returncode:
            raise SystemExit(result.stderr + result.stdout)
        compiled = output_path.read_text() if node else result.stdout.strip()
    shell = (ROOT / 'src/shell.html').read_text()
    html = '<!-- Generated by tools/build.py. Edit src/ files, then rebuild. -->\n' + shell.replace(
        '/* STYLES */', (ROOT / 'src/styles.css').read_text()
    ).replace('/* APPLICATION */', compiled.replace('</script', '<\\/script'))
    (ROOT / 'esipk_dashboard.html').write_text(html)
    print(f'Built esipk_dashboard.html: {len(html.encode()):,} bytes from {len(SOURCES)} source files.')

if __name__ == '__main__':
    build()
